#!/bin/bash

# Skrypt pre-push hooka dla automatycznego deploymentu strony Hugo
echo "Rozpoczynam proces deploymentu strony Hugo..."

# Sprawdź czy to ręczne uruchomienie
if [ "$1" = "manual" ]; then
  cd "$(pwd)" || exit 1
else
  # Przejdź do katalogu głównego projektu
  cd "$(git rev-parse --show-toplevel)" || exit 1
fi

# Budowanie strony Hugo
echo "Budowanie strony Hugo..."
hugo || { echo "Błąd podczas budowania strony Hugo!"; exit 1; }

# Czyszczenie zdalnego katalogu przed deploymentem
echo "Czyszczenie zdalnego katalogu..."
ssh <user@ip> 'rm -rf <folder>nginx/homepage/*' || { echo "Błąd podczas czyszczenia zdalnego katalogu!"; exit 1; }

# Kopiowanie plików na serwer
echo "Kopiowanie plików na serwer..."
rsync -avz --delete --checksum ./public/* <lokalizacja> || { echo "Błąd podczas kopiowania plików!"; exit 1; }

echo "Deployment zakończony sukcesem!"
exit 0
